Labels
linkedinlabs/stapler-figma pull request #13
Opened 2021-01-23 00:00 UTC by lynnerang

2021-01-25 21:48 UTC, lynnerang commented on src/additionalTypes.d.ts
> +  type PresenterAriaLabels = {
Still not 100% on the name, but went with AriaLabels for now in an attempt to make it clear what kind of labels these are.  Any other suggestions are welcome!

2021-01-25 21:52 UTC, lynnerang commented on src/views/ComponentData.svelte
> +    labelText="Role"
Mainly did this to match Specter, but maybe both should have it?  What do ya reckon?

2021-01-25 21:55 UTC, lynnerang commented on src/views/ItemsList.svelte
> +              editorComponentData[key] = key === 'labels' ? { ...item.componentData[key] } : item.componentData[key];
I'm not loving what I did for this, am considering coming back to it to see if there's a data-type-agnostic way I could ensure vals w/o references on complex data types in case this grows and includes more objects and such later on?

2021-01-25 21:57 UTC, lynnerang commented on src/views/ItemsList.svelte
> +                    !(!editorComponentData.labels[labelKey] && !val)
Ended up adding this to account for the possibility that one is on the unset **null** value and the other was deleted to an empty string.

2021-01-25 21:58 UTC, lynnerang commented on src/views/forms-controls/FigmaSwitch.svelte
> +        <span class="fa fa-exclamation-circle warning"/>
Do you mind that I added the fontAwesome CDN script tag?  I have a thang for font icons, but I know they aren't everyone's cuppa.

2021-01-26 01:12 UTC, gblakeman requested changes
🎉👊

Good stuff – some minor changes, formatting stuff, and a few questions.

2021-01-26 01:12 UTC, gblakeman commented on src/views/ComponentData.svelte
> +  const setClasses = (classes, hasMultiple) => {
I updated this… `hasValues` just wasn’t working in my brain anymore.

2021-01-26 01:12 UTC, gblakeman commented on src/views/forms-controls/FormUnit.svelte
> +  export let preserveDirtyProp; // temp way to avoid updates for component with new prop-based updates
By “temp” do you mean that you think there should be a different way to achieve this? Or that ultimately it’s the path forward, but needs to be implemented elsewhere to retire the `resetValue` convention?

2021-01-26 18:13 UTC, lynnerang commented on src/views/ItemsList.svelte
> +              editorComponentData[key] = key === 'labels' ? { ...item.componentData[key] } : item.componentData[key];
maybe combo w/ Array.isArray()?

2021-01-26 21:08 UTC, gblakeman commented on src/views/ItemsList.svelte
> +              editorComponentData[key] = typeof editorComponentData[key] === 'object'
@lynnerang Maybe this is overkill, but as I was thinking through the `typeof thing === 'object'` issue I realized that we should probably also account for arrays here too. So why not just use the `=== 'object'` check and then the `deepCopy` helper to ensure _both_ arrays and objects get copied without references?

2021-01-27 17:44 UTC, gblakeman commented on src/Presenter.ts
> +          // check for old `role` data and migrate
@lynnerang I think you’d asked about this particular case and I said don’t worry about it – but then ran into it in my own testing, so I figured it didn’t hurt to add an exception that handled it. 🤷🏻‍♂️

2021-01-27 17:52 UTC, gblakeman approved these changes
I’m thinking this is ready to go! 🙌

2021-01-27 18:37 UTC, lynnerang commented on src/views/ItemsList.svelte
> +              editorComponentData[key] = typeof editorComponentData[key] === 'object'
oh sweet, I didn't realize deepCopy handled both.  this seems perfect!

2021-01-27 19:40 UTC, merged