CSV token value import feature
linkedinlabs/stapler-figma pull request #32
Opened 2021-06-08 20:02 UTC by joeyyang

This PR makes the following changes:
- Adds a "Import Token Values" menu option and "Style Import" tab to main Stapler window with CSV import window
- CSV import window\ accepts raw CSV string and converts into Figma styles (`PaintStyle`s)

I wanted to put the initial pass up for review - I appreciate any and all feedback, including but not limited to, file and method organization, parsing methodology, view logic, UI organization, technical approach, styles, and anything else you see.

I still need to complete the styling for this work, but I wanted to put this initial pass up for review first.

<img width="1708" alt="Screen Shot 2021-06-08 at 12 55 19 PM" src="https://user-images.githubusercontent.com/2928395/121248958-e2a3e080-c858-11eb-96cf-5c6ec0cad78c.png">
<img width="1703" alt="Screen Shot 2021-06-08 at 12 55 47 PM" src="https://user-images.githubusercontent.com/2928395/121248929-da4ba580-c858-11eb-8920-c9b50bb13817.png">

2021-06-08 20:05 UTC, joeyyang commented on src/code.ts
> +        App.showGUI({});
This almost certainly isn't the right function call - how would I call a method that takes me to the correct tab in the plugin window?

2021-06-08 20:05 UTC, joeyyang commented on src/code.ts
> +        App.displayStyleValues(payload);
should I be routing the second part of the CSV import logic through the main `code.ts` `switch`/`case` statement?

2021-06-08 20:06 UTC, joeyyang commented on src/views/App.svelte
> +    <StyleImport />
totally not sure how to handle the UI behavior here - I want the `StyleImport` component to show only when I've clicked the "Import Token Values" menu option or the "Style Import" tab in the UI

2021-06-08 20:07 UTC, joeyyang commented on src/additionalTypes.d.ts
> +    | 'Style Import';
do I need this?

2021-06-08 20:08 UTC, joeyyang commented on src/App.ts
> +      const styleColor: RGB = {
Pretty sure between this type declaration and the next `SolidPaint` assignment I'm butchering the type system here

2021-06-08 20:18 UTC, joeyyang commented on src/Tools.ts
> +    r: number,
this looks weird but i'm not sure how to get this to pass the linter otherwise - is there a more convenient syntax here?

2021-06-08 23:39 UTC, gblakeman commented on src/code.ts
> +        App.showGUI({});
Kinda related to you question in `App.svelte`, I think we should have a separate function in the `App` class that is specific to spinning up this CSV Import UI, rather than using the generic `showGUI`. It’ll likely be very simple and similar to the existing `showToolbar` function.

2021-06-09 00:40 UTC, gblakeman commented on src/Tools.ts
> +    r: number,
Could just truncate it to one line, maybe?

```javascript
  const decimalRgb: {
    r: number, g: number, b: number, a: number,
  } = {
    r, g, b, a,
  };
```

2021-06-09 02:27 UTC, joeyyang commented on src/code.ts
> +        App.displayStyleValues(payload);
great!

2021-06-09 19:30 UTC, gblakeman requested changes
Awesome work!

I know this is not final code, so many of my comments may cover things you would normally hit as well. I just wanted to make sure we have those discussion points.

The big thing I would consider changing is repetitive nature between your `convertHexToDecimal` and the pre-existing `hexToDecimalRgb`. I think there’s a lot of duplicated work there that could be combined somehow.

2021-06-09 19:30 UTC, gblakeman commented on src/Tools.ts
> +      .slice(1, -1) // take off "" marks first
Love the inline comments; thank you!!

2021-06-09 19:30 UTC, gblakeman commented on src/Tools.ts
> +const convertHexToDecimal = (hexValue: {
I feel like this is doing almost exactly what `hexToDecimalRgb` is doing after it converts the hex into `rgba`.

Maybe it would make sense to create a `rgbToDecimalRgb` function from the guts of `hexToDecimalRgb`? You could then use it for these `rgba` conversions and turn `hexToDecimalRgb` into much shorter function:

```javascript
const rgbColor = hexRgb(hexColor);
const decimalRgb = rgbToDecimalRgb(rgbColor);
return decimalRgb;
```

2021-06-09 19:30 UTC, gblakeman commented on src/App.ts
> +    function CSVToArray(strData) {
Something for our discussion later today – at this point I’m a fan of trying to set to ES6 arrow-style functions for consistency across the board.

/cc @lynnerang

2021-06-09 19:30 UTC, gblakeman commented on src/App.ts
> +        const [first, ...rest] = line.split(',');
Some inline comments in this block would help to understand what we’re parsing.

2021-06-09 19:30 UTC, gblakeman commented on src/App.ts
> +      const styleColor: RGB = {
These came out of Figma’s typings, correct? I think anything in there is fair game for use.

2021-06-09 19:30 UTC, gblakeman commented on src/App.ts
> +      const parsedStyleValue = parseStyleValue(styleValue);
Should this have a type?

2021-06-09 19:30 UTC, gblakeman commented on src/App.ts
> +      const figmaPaintStyle = figma.createPaintStyle();
Probably should have the `PaintStyle` type.

2021-06-09 22:28 UTC, lynnerang commented on src/App.ts
> +        const [first, ...rest] = line.split(',');
Wanted to say, this is super cool.  I didn't realize you could destructure an array with the spread operator like you have here, neat trick!

2021-06-09 22:36 UTC, lynnerang commented on src/views/App.svelte
> +    if (wasBodyHeight !== bodyHeight && selected && selected.items.length > 0) {
very insignificant detail here, but I wanted to take the opportunity ask you guys your thoughts on optional chaining and truthy/falsey checks in cases like these? 

`if (wasBodyHeight !== bodyHeight && selected?.items.length) {}`

I'm somewhat on the fence about operational chaining in particular, since it's sometimes not supported within JS frameworks' component templates.  buuut I also kind of love it and feel compelled use it where I can?

2021-06-10 18:17 UTC, joeyyang commented on src/views/App.svelte
> +    if (wasBodyHeight !== bodyHeight && selected && selected.items.length > 0) {
yes! i love the `?` pattern for checking, so glad that javascript supports this now

2021-06-10 20:43 UTC, gblakeman commented on src/views/App.svelte
> +    if (wasBodyHeight !== bodyHeight && selected && selected.items.length > 0) {
Oh, fun! I didn’t realize js supported this now.

2021-06-11 05:16 UTC, joeyyang commented on tsconfig.json
> +      "./node_modules/@figma"
needed to add these so the code would recognize the Figma `RGBA` type

2021-06-11 05:18 UTC, joeyyang commented
hi @gblakeman @lynnerang - addressed your comments, please review! Let me know anything else that can be improved.

2021-06-11 15:07 UTC, lynnerang commented
Looks great Joey, thanks for sharing!

2021-06-11 16:44 UTC, gblakeman commented on tsconfig.json
> +      "./node_modules/@figma"
@joeyyang Are you getting errors in either `watch` or your local IDE? On my end, this is covered by lines `5` and `7` in the `types` declaration and `RGB` and `RGBA` are recognized by the compiler.

2021-06-11 16:54 UTC, gblakeman approved these changes
🎉👊

Awesome work Joey! Just a quibble with naming/docs. I’d also like to make sure we don’t unnecessarily add the new `typeRoots` stuff to `tsconfig.json`, so let me know what you’re seeing on your end without that config update. Maybe there’s a fix?

2021-06-11 16:54 UTC, gblakeman commented on src/Tools.ts
> +const convertHexToDecimal = (hexValue: RGBA): RGBA => {
I love the way you’ve updated `hexToDecimalRgb` to use this function, but could we rename it? `convertHexToDecimal` is actually taking an RGB color and converting it to Figma’s decimal color system. Hexadecimal isn’t involved at this point.

2021-06-11 16:54 UTC, gblakeman commented on src/Tools.ts
> + * Converts an rgba color value encoded in hexademical ([0, 255]) to a decimal
I think this doc needs to be updated (it’s the same as `hexToDecimalRgb`). We can probably just omit “encoded in hexademical ([0, 255])” and it’ll be more representative of what the function is doing.

2021-06-11 19:14 UTC, merged